server:
  servlet:
    context-path: /api/v1/


spring:
  datasource:
    url: jdbc:mariadb:tcp://localhost/~/mocoo-mocoo
    username: root
    password: mocoomocoo
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json