server:
  servlet:
    context-path: /api/v1/


spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mocoo?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: wonniee
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json